# Generated by Django 5.0.6 on 2024-07-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('Kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umkm', to='api.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField()),
                ('Kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='api.kategori')),
                ('UMKM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='api.umkm')),
            ],
        ),
    ]
