# Generated by Django 5.0.6 on 2024-05-14 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='UMKM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umkm', to='api.umkm'),
        ),
    ]
